import type { Metadata } from "next";
import { Barlow_Condensed } from "next/font/google";
import NavBar from '@/components/NavBar';
import "./globals.css";
import GlobalEffects from "../components/GlobalEffects";
import StarField from '@/components/StarField';

const fontSans = Barlow_Condensed({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "ma creation",
  description: "generated by me",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} mx-auto px-20 antialiased bg-background text-foreground`}>
		<div className="relative min-w-[1080px] m-auto px-4 border-x-1 border-white/20 overflow-hidden">
			<NavBar logo={false}></NavBar>
			{children}
		</div>
      </body>
    </html>
  );
}
