import type { Metadata } from "next";
import { Ibarra_Real_Nova, Barlow_Condensed, Comfortaa } from "next/font/google";
import NavBar from '@/components/NavBar';
import "./globals.css";
import GlobalEffects from "../components/GlobalEffects";
import StarField from '@/components/StarField';
import VideoBackground from "@/components/VideoBackground";
import StarrySky from "@/components/StarrySky";

const ibarraRealNova = Ibarra_Real_Nova({
  variable: "--font-title",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const barlowCondensed = Barlow_Condensed({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const fontComfortaa = Comfortaa({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "ma creation",
  description: "generated by me",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

	return (
	<html lang="en" className={`${ibarraRealNova.variable} ${barlowCondensed.variable}`}>
		<body className={`mx-auto antialiased bg-background text-foreground`}>
			<StarrySky>
				<NavBar logo={true} />
				<GlobalEffects>
					<div className="relative mx-20 min-w-[1080px] m-auto overflow-hidden">
						{children}
					</div>
				</GlobalEffects>
			</StarrySky>
		</body>
	</html>
  );
}
